spring:
  application:
    name: spot-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    open-in-view: false
    generate-ddl: true
  config:
    import: 'optional:configserver: '
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server


#eureka:
#  instance:
#    prefer-ip-address: false
#    hostname: ecs-load-balancer-597540403.ap-northeast-2.elb.amazonaws.com
#    non-secure-port: 3500
#    health-check-url-path: /actuator/health

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    non-secure-port: 3500
    health-check-url-path: /actuator/health

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.79.151.83:3150/eureka/

server:
  port: 3500